# Generated by Django 3.0.8 on 2020-07-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaPost', '0002_auto_20200712_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
