# Generated by Django 3.0.8 on 2020-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instauser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instauser',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
